version: '3'

services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: car_notificator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - C:\docker-volumes\postgres:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:3.6.2
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  project-builder:
    build:
      context: .
      dockerfile: Dockerfile

  user-service:
    build:
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - project-builder
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car_notificator
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/car_notificator
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  observer-service:
    build:
      context: observer-service
      dockerfile: Dockerfile
    depends_on:
      - user-service
    environment:
      FEIGN_NOTIFICATION_SERVICE_URL: notification-service:8081
      FEIGN_USER_SERVICE_URL: user-service:8080

  notification-service:
    build:
      context: notification-service
      dockerfile: Dockerfile
    depends_on:
      - user-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FEIGN_USER-SERVICE_URL: user-service:8080